aws_color_primary=$command_color_primary_highlight
aws_color_seconday=$host_color_primary_highlight

command_color_primary="134;150;150"
command_color_primary_highlight="255;90;103"
command_color_secondary="0;56;77"
command_color_secondary_highlight=$command_color_primary

conda_color_primary=$command_color_primary_highlight
conda_color_seconday=$host_color_primary_highlight

direnv_color_primary=$path_color_primary
direnv_color_secondary="250;250;248"

exit_code_color_primary_highlight=$command_color_secondary
exit_code_color_secondary="196;48;96"

git_color_primary="255;204;27"
git_color_secondary=$command_color_secondary

host_color_primary="81;127;141"
host_color_primary_highlight="240;142;72"
host_color_secondary="161;161;154"
host_color_secondary_highlight="0;38;53"

k8s_color_primary="108;139;145"
k8s_color_secondary=$direnv_color_secondary

load_color_primary=$host_color_primary_highlight
load_color_primary_highlight=$command_color_primary_highlight
load_color_secondary=$command_color_secondary
load_color_secondary_highlight=$direnv_color_secondary

nix_color_primary="93;215;185"
nix_color_secondary=$direnv_color_secondary

path_color_primary="154;112;164"
path_color_secondary=$direnv_color_secondary
path_color_splitter=$command_color_primary

path_ro_color_primary=$command_color_secondary
path_ro_color_secondary=$exit_code_color_secondary

prompt_ready_color_secondary=$command_color_primary

python_env_color_primary=$host_color_primary_highlight
python_env_color_secondary=$exit_code_color_secondary

rescuetime_color_primary="127;192;110"
rescuetime_color_secondary=$command_color_primary
rescuetime_color_splitter=$direnv_color_secondary

terraform_color_primary=$host_color_primary
terraform_color_secondary=$host_color_secondary

timestamp_color_primary=$host_color_primary
timestamp_color_secondary=$host_color_secondary

wttr_color_primary=$rescue_time_primary
wttr_color_secondary=$command_color_primary
wttr_color_splitter=$direnv_color_secondary
