aws_color_primary=$command_color_primary_highlight
aws_color_seconday=$host_color_primary_highlight

command_color_primary="165;159;133"
command_color_primary_highlight="249;38;114"
command_color_secondary="56;56;48"
command_color_secondary_highlight=$command_color_primary

conda_color_primary=$command_color_primary_highlight
conda_color_seconday=$host_color_primary_highlight

direnv_color_primary=$path_color_primary
direnv_color_secondary="249;248;245"

exit_code_color_primary_highlight=$command_color_secondary
exit_code_color_secondary="204;102;51"

git_color_primary="244;191;117"
git_color_secondary=$command_color_secondary

host_color_primary="73;72;62"
host_color_primary_highlight="253;151;31"
host_color_secondary="248;248;242"
host_color_secondary_highlight="39;40;34"

k8s_color_primary="117;113;94"
k8s_color_secondary=$direnv_color_secondary

load_color_primary=$host_color_primary_highlight
load_color_primary_highlight=$command_color_primary_highlight
load_color_secondary=$command_color_secondary
load_color_secondary_highlight=$direnv_color_secondary

nix_color_primary="102;217;239"
nix_color_secondary=$direnv_color_secondary

path_color_primary="174;129;255"
path_color_secondary=$direnv_color_secondary
path_color_splitter=$command_color_primary

path_ro_color_primary=$command_color_secondary
path_ro_color_secondary=$exit_code_color_secondary

prompt_ready_color_secondary=$command_color_primary

python_env_color_primary=$host_color_primary_highlight
python_env_color_secondary=$exit_code_color_secondary

rescuetime_color_primary="166;226;46"
rescuetime_color_secondary=$command_color_primary
rescuetime_color_splitter=$direnv_color_secondary

terraform_color_primary=$host_color_primary
terraform_color_secondary=$host_color_secondary

timestamp_color_primary=$host_color_primary
timestamp_color_secondary=$host_color_secondary

wttr_color_primary=$rescue_time_primary
wttr_color_secondary=$command_color_primary
wttr_color_splitter=$direnv_color_secondary
