aws_color_primary=$command_color_primary_highlight
aws_color_seconday=$host_color_primary_highlight

command_color_primary="131;148;150"
command_color_primary_highlight="220;50;47"
command_color_secondary="7;54;66"
command_color_secondary_highlight=$command_color_primary

conda_color_primary=$command_color_primary_highlight
conda_color_seconday=$host_color_primary_highlight

direnv_color_primary=$path_color_primary
direnv_color_secondary="253;246;227"

exit_code_color_primary_highlight=$command_color_secondary
exit_code_color_secondary="211;54;130"

git_color_primary="181;137;0"
git_color_secondary=$command_color_secondary

host_color_primary="88;110;117"
host_color_primary_highlight="203;75;22"
host_color_secondary="147;161;161"

k8s_color_primary="101;123;131"
k8s_color_secondary=$direnv_color_secondary

load_color_primary=$host_color_primary_highlight
load_color_primary_highlight=$command_color_primary_highlight
load_color_secondary=$command_color_secondary
load_color_secondary_highlight=$direnv_color_secondary

nix_color_primary="38;139;210"
nix_color_secondary=$direnv_color_secondary

path_color_primary="108;113;196"
path_color_secondary=$direnv_color_secondary
path_color_splitter=$command_color_primary

path_ro_color_primary=$command_color_secondary
path_ro_color_secondary=$exit_code_color_secondary

prompt_ready_color_secondary=$command_color_primary

python_env_color_primary=$host_color_primary_highlight
python_env_color_secondary=$exit_code_color_secondary

rescuetime_color_primary="133;153;0"
rescuetime_color_secondary=$command_color_primary
rescuetime_color_splitter=$direnv_color_secondary

terraform_color_primary=$host_color_primary
terraform_color_secondary=$host_color_secondary

timestamp_color_primary=$host_color_primary
timestamp_color_secondary=$host_color_secondary

wttr_color_primary=$rescue_time_primary
wttr_color_secondary=$command_color_primary
wttr_color_splitter=$direnv_color_secondary
